name: Smoke test daily
on:
  schedule:
    - cron: '25 3 * * *'
jobs:
  login-run:
    name: Daily smoke test on trunk.
    runs-on: ubuntu-18.04
    steps:

      - name: Create dirs.
        run: |
              mkdir -p code/woocommerce
              mkdir -p package/woocommerce
              mkdir -p tmp/woocommerce
              mkdir -p node_modules

      - name: Checkout code.
        uses: actions/checkout@v2
        with:
          ref: trunk

      - name: Install prerequisites.
        run: |
          npm install
          composer install --no-dev
          npm run build:assets
          npm install jest

      - name: Get the latest WooCommerce nightly zip.
        run: |
          cd ${{ github.workspace }}/tests/e2e/env/deps && { curl -LO "https://github.com/woocommerce/woocommerce/releases/download/nightly/woocommerce-trunk-nightly.zip" ; cd -; }

      - name: Validate the zip file.
        run: ./.github/scripts/validate-zip.sh
        shell: bash
          
      - name: Run smoke test.
        env:
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_URL }}
          SMOKE_TEST_ADMIN_USER: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
          SMOKE_TEST_ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
          SMOKE_TEST_CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
          SMOKE_TEST_CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
          WC_E2E_SCREENSHOTS: 1
          E2E_RETEST: 1
          E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
          E2E_SLACK_CHANNEL: ${{ secrets.SMOKE_TEST_SLACK_CHANNEL }}
          INSTALL_WC_PLUGIN: 1
        run: |
          npx wc-e2e test:e2e
